[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dropbox>=12.0.2",
    "flask>=3.1.2",
    "numpy>=2.3.5",
    "retrying>=1.4.2",
    "tenseal>=0.3.16",
]
